# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Print Welcome Tweets"

on: [push, pull_request]

jobs:
  print_welcome_tweets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'
      - run: npm ci
      - run: node scripts/print_welcome_tweets.js
